### ISSUE TITLE
Crash when losing focus on property entry

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#133]
Non-reproducible, what happened:

1. Create property
1. Remove title (empty text field)
1. Drop down type
1. Select type
1. Crash

```
09-22 11:53:37.314 23546-23546/net.twisterrob.inventory.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.twisterrob.inventory.debug, PID: 23546
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference
        at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:78)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:362)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by TWiStErRob** [comment]
Debug-only problem; just disable advanced profiling: https://stackoverflow.com/a/49978463/253468
