### ISSUE TITLE
Tests containing setType may fail

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#140]
found in svn2776 on Nexus_5X_API_21(AVD) - 5.0.2
> probably: // TODO tests containing setType may fail for Item when run with animations enabled and running in landscape
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at net.twisterrob.inventory.android.test.actors.EditActivityActor.setType(EditActivityActor.java:75)
at net.twisterrob.inventory.android.activity.EditActivityTest_Create.testTypeSavedAfterChange(EditActivityTest_Create.java:137)
```

**Comment by TWiStErRob** [comment]
Duplicate of #153
