### ISSUE TITLE
Gallery picker crashes on Android 10

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#148]

**Comment by TWiStErRob** [comment]
```
2020-01-17 01:44:49.312 8270-8270/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android:ui, PID: 8270
    java.lang.RuntimeException: Unable to start activity ComponentInfo{android/com.android.internal.app.ChooserActivity}: java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
        at com.android.internal.app.ResolverActivity$ResolveInfoPresentationGetter.getAppSubLabelInternal(ResolverActivity.java:715)
        at com.android.internal.app.ResolverActivity$TargetPresentationGetter.getSubLabel(ResolverActivity.java:666)
        at com.android.internal.app.ResolverActivity$ActivityInfoPresentationGetter.getSubLabel(ResolverActivity.java:726)
        at com.android.internal.app.ChooserActivity$ChooserListAdapter.<init>(ChooserActivity.java:2409)
        at com.android.internal.app.ChooserActivity.createAdapter(ChooserActivity.java:1861)
        at com.android.internal.app.ResolverActivity.configureContentView(ResolverActivity.java:1253)
        at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:333)
        at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:608)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by TWiStErRob** [comment]
This line
https://android.googlesource.com/platform/frameworks/base.git/+/android10-release/core/java/com/android/internal/app/ResolverActivity.java#715
from this commit
https://android.googlesource.com/platform/frameworks/base.git/+/9c4ae502550609565a4ae2568eb638ce31e4f5bc%5E%21/core/java/com/android/internal/app/ResolverActivity.java
broke the `CharSequence` being able to load as the intent title because of a cast to `String`.

**Comment by TWiStErRob** [comment]
Preparation: externalize strings into `strings.xml` (using `TextTools#formatFormatted` because there are placeholders and styling)

Workaround: remove formatting in a `values-v29` override:
```
values/strings.xml

	<string name="pick"><xliff:g id="app" example="Photos">%1$s</xliff:g> <font color="#CCCCCC">(select)</font></string>

values-v29/strings.xml

	<string name="pick"><xliff:g id="app" example="Photos">%1$s</xliff:g> (select)</string>
```

At this point `Resources.getText` will still return a `Spannable`, but we can interrogate it if it has styling (`getSpans(0, seq.length(), Object.class)`) and fall back to `String` which will be accepted by Android 10.

**Comment by TWiStErRob** [comment]
https://mail.google.com/mail/u/0/?zx=phceznxu07lo#label/Inbox%2FInventory/FMfcgxwHMPndwDvqrGPXgdmTldwHFXWW

**Comment by TWiStErRob** [comment]
https://mail.google.com/mail/u/0/?zx=phceznxu07lo#sent/FMfcgxwHMPmTtRPQQnXSdTRqRkjfgQzk

**Comment by TWiStErRob** [comment]
https://mail.google.com/mail/u/0/?zx=a7o67nv9bjkj#inbox/FMfcgxwHMZNWmTkqbVhxkfLrnlGKNBjv

**Comment by TWiStErRob** [comment]
https://mail.google.com/mail/u/0/?zx=a7o67nv9bjkj#inbox/FMfcgxwHMsZhlDMnltSXphDsVlmcZrhQ
