### ISSUE TITLE
Flaky ItemEditActivityTest_CreateInRoom.testTypeSavedAfterChange

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#153]
Sometimes this test fails on API 21 (40% on :connectedCheck, 10% on manual execution).
```
at net.twisterrob.inventory.android.test.actors.EditActivityActor.setType(EditActivityActor.java:75)
at net.twisterrob.inventory.android.activity.EditActivityTest_Create.testTypeSavedAfterChange(EditActivityTest_Create.java:137)
```

**Comment by TWiStErRob** [comment]
Setting the type in spinner the second time doesn't always work. The popup stays open.
```java
		editor.setType(belonging.getType());
		editor.setType(belonging.getOtherType());
```
Got this info from looking at screenshots and listing roots:
```java
	for (Root root : EspressoExtensions.getRoots()) {
		longLog("ROOTS", "Root: " + root + "\n" + HumanReadables
				.getViewHierarchyErrorMessage(root.getDecorView(), null, "", null));
	}

	private void longLog(String tag, String message) {
		int LOGGER_ENTRY_MAX_PAYLOAD = 4076;
		while (message.length() > LOGGER_ENTRY_MAX_PAYLOAD) {
			Log.e(tag, message.substring(0, LOGGER_ENTRY_MAX_PAYLOAD));
			message = message.substring(LOGGER_ENTRY_MAX_PAYLOAD).trim();
		}
		Log.e(tag, message);
	}
```

The first Root after the second ViewInteraction shouldn't be there.
```
I/ViewInteraction: Performing 'single click' action on view  displaying data matching: with String column named "name" that is "category_computer_part" within adapter view matching: is assignable from class: class android.widget.AdapterView

E/ROOTS: Root: Root{application-window-token=android.view.ViewRootImpl$W@43f8f57, window-token=android.view.ViewRootImpl$W@43f8f57, has-window-focus=true, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#12 ty=1 fl=#81810100 pfl=0x8 wanim=0x1030461 surfaceInsets=Rect(0, 0 - 0, 0)}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#12 ty=1 fl=#81810100 pfl=0x8 wanim=0x1030461 surfaceInsets=Rect(0, 0 - 0, 0)}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}

I/ViewInteraction: Performing 'single click' action on view  displaying data matching: with String column named "name" that is "category_book" within adapter view matching: is assignable from class: class android.widget.AdapterView

E/ROOTS: Root: Root{application-window-token=android.view.ViewRootImpl$W@43f8f57, window-token=android.view.ViewRootImpl$W@3bb6d575, has-window-focus=true, layout-params-type=1002, layout-params-string=WM.LayoutParams{(11,570)(932x1160) gr=#10000033 sim=#1 ty=1002 fl=#1860200 fmt=-3 wanim=0x10302db surfaceInsets=Rect(0, 0 - 0, 0)}, decor-view-string=PopupViewContainer{id=-1, visibility=VISIBLE, width=932, height=1160, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(11,570)(932x1160) gr=#10000033 sim=#1 ty=1002 fl=#1860200 fmt=-3 wanim=0x10302db surfaceInsets=Rect(0, 0 - 0, 0)}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}

E/ROOTS: Root: Root{application-window-token=android.view.ViewRootImpl$W@43f8f57, window-token=android.view.ViewRootImpl$W@43f8f57, has-window-focus=false, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#12 ty=1 fl=#81810100 pfl=0x8 wanim=0x1030461 surfaceInsets=Rect(0, 0 - 0, 0)}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#12 ty=1 fl=#81810100 pfl=0x8 wanim=0x1030461 surfaceInsets=Rect(0, 0 - 0, 0)}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}
```

**Comment by TWiStErRob** [comment]
Closed in svn@3120 by trying to click again if the popup didn't close the first time.
