### ISSUE TITLE
Incompatible tests on API26-29: BackupActivityTest_ExportInternal

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#154]
```
java.io.IOException: Permission denied
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createTempFile(File.java:2001)
at org.junit.rules.TemporaryFolder.createTemporaryFolderIn(TemporaryFolder.java:237)
at org.junit.rules.TemporaryFolder.create(TemporaryFolder.java:147)
at org.junit.rules.TemporaryFolder.before(TemporaryFolder.java:133)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
at net.twisterrob.android.test.junit.IdlingResourceRule$IdlingResourceStatement.evaluate(IdlingResourceRule.java:42)
at net.twisterrob.android.test.junit.IdlingResourceRule$IdlingResourceStatement.evaluate(IdlingResourceRule.java:42)
at net.twisterrob.android.test.espresso.ScreenshotFailure$ScreenshotStatement.evaluate(ScreenshotFailure.java:94)
at net.twisterrob.android.test.junit.SensibleActivityTestRule$TestLogger$1.evaluate(SensibleActivityTestRule.java:137)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at net.twisterrob.android.test.junit.IdlingResourceRule$IdlingResourceStatement.evaluate(IdlingResourceRule.java:42)
```

**Comment by TWiStErRob** [comment]
Fixed in svn@3122 by granting permission:
```
adb shell pm grant net.twisterrob.inventory.test android.permission.WRITE_EXTERNAL_STORAGE
```
