### ISSUE TITLE
GlideIdlingResource is flaky on API26-29

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#155]
```
java.lang.IllegalStateException: com.bumptech.glide.load.engine.EngineJob@5aeae2c doesn't have an end listener ([com.bumptech.glide.request.GenericRequest@c2fcc72])
at com.bumptech.glide.load.engine.EngineExternalLifecycle.getSignUp(EngineExternalLifecycle.java:124)
at com.bumptech.glide.load.engine.EngineExternalLifecycle.finishing(EngineExternalLifecycle.java:60)
at com.bumptech.glide.load.engine.EngineExternalLifecycle.access$500(EngineExternalLifecycle.java:19)
at com.bumptech.glide.load.engine.EngineExternalLifecycle$EngineJobsReplacement.remove(EngineExternalLifecycle.java:189)
at com.bumptech.glide.load.engine.EngineExternalLifecycle$EngineJobsReplacement.remove(EngineExternalLifecycle.java:180)
at com.bumptech.glide.load.engine.Engine.onEngineJobComplete(Engine.java:268)
at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:153)
at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:160)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:472)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:381)
```

**Comment by TWiStErRob** [comment]
![image](https://user-images.githubusercontent.com/2906988/79025248-1748d900-7b7d-11ea-8d7d-2cf9480e0251.png)

**Comment by TWiStErRob** [comment]
`EngineJobsReplacement` wasn't intercepting the `Map.put`s, because of this commit: https://android.googlesource.com/platform/libcore.git/+/9efb6d12ce4d2ffedb73d6e9887ea2c89f8ec129%5E%21/#F8
before the change `fun putAll(map) = map.forEach(::put)`, after it's
```
fun putAll(map) = map.entries.forEach(::putVal)
fun put(k, v) = putVal(k, v)
```
but `putVal` is not overridable.

**Comment by TWiStErRob** [comment]
Fixed in svn@3127
