### ISSUE TITLE
Missing theme setup for NavigationView

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#156]
API 29 (no Play)
```
2020-04-11 00:31:55.323 6165-6165/? W/Resources: ColorStateList android:color/text_color_secondary has unresolved theme attributes! Consider using Resources.getColorStateList(int, Theme) or Context.getColorStateList(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getColorStateList(Resources.java:1020)
        at android.support.design.widget.NavigationView.createDefaultColorStateList(NavigationView.java:416)
        at android.support.design.widget.NavigationView.<init>(NavigationView.java:127)
        at android.support.design.widget.NavigationView.<init>(NavigationView.java:96)
        at net.twisterrob.android.view.NavigationView.<init>(NavigationView.java:17)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at net.twisterrob.inventory.android.activity.DrawerActivity.createDrawerLeft(DrawerActivity.java:78)
        at net.twisterrob.inventory.android.activity.DrawerActivity.initDrawers(DrawerActivity.java:64)
        at net.twisterrob.inventory.android.activity.DrawerActivity.onContentChanged(DrawerActivity.java:49)
        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:281)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at net.twisterrob.inventory.android.activity.MainActivity.onCreate(MainActivity.java:86)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:667)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by TWiStErRob** [comment]
It's only a warning with stack trace, see `android.content.res.Resources#getColorStateList(int)`

**Comment by TWiStErRob** [comment]
Does not reproduce after #260
