### ISSUE TITLE
Hide "Camera (capture)" when permission is denied

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#158]
![image](https://user-images.githubusercontent.com/2906988/79045284-3c335f80-7c02-11ea-8551-105ae4e4df3c.png)

**Comment by TWiStErRob** [comment]
```
2052-2082/? I/ActivityManager: Start proc 18127:com.android.systemui:ui/u0a105 for activity {com.android.systemui/com.android.systemui.chooser.ChooserActivity}
2052-3052/? I/ActivityTaskManager: START u0 {act=android.media.action.IMAGE_CAPTURE flg=0x3000003 pkg=com.android.camera2 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://net.twisterrob.inventory.debug.share/temp/temp_0.jpg} (has extras)} from uid 10136
2052-3052/? W/ActivityTaskManager: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3000003 pkg=com.android.camera2 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://net.twisterrob.inventory.debug.share/temp/temp_0.jpg} (has extras) } from null (pid=-1, uid=10136) with revoked permission android.permission.CAMERA
18127-18127/? D/AndroidRuntime: Shutting down VM
18127-18127/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui:ui, PID: 18127
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.chooser.ChooserActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3000003 pkg=com.android.camera2 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://net.twisterrob.inventory.debug.share/temp/temp_0.jpg} (has extras) } from null (pid=-1, uid=10136) with revoked permission android.permission.CAMERA
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3000003 pkg=com.android.camera2 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://net.twisterrob.inventory.debug.share/temp/temp_0.jpg} (has extras) } from null (pid=-1, uid=10136) with revoked permission android.permission.CAMERA
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivityAsCaller(IActivityTaskManager.java:4308)
        at android.app.Instrumentation.execStartActivityAsCaller(Instrumentation.java:1961)
        at android.app.Activity.startActivityAsCaller(Activity.java:5359)
        at com.android.systemui.chooser.ChooserHelper.onChoose(ChooserHelper.java:49)
        at com.android.systemui.chooser.ChooserActivity.onCreate(ChooserActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1043)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:760)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:583)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1288)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:514)
```
and `onActivityResult(RESULT_CANCELED)` is called
