### ISSUE TITLE
Backup doesn't work with targetSdkVersion=23+

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#159]
```
I/BackupService: Finished with: Finished: data=0/0 images=0/0, pending, 0 warnings, java.io.FileNotFoundException: /storage/emulated/0/Download/Inventory_2020-04-11_14-58-07.zip: open failed: EACCES (Permission denied)
    java.io.FileNotFoundException: /storage/emulated/0/Download/Inventory_2020-04-11_14-58-07.zip: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at net.twisterrob.inventory.android.backup.exporters.BackupFileExporter.exportTo(BackupFileExporter.java:24)
        at net.twisterrob.inventory.android.backup.exporters.BackupDirExporter.exportTo(BackupDirExporter.java:24)
        at net.twisterrob.inventory.android.backup.concurrent.BackupService.onHandleIntent(BackupService.java:140)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
        at net.twisterrob.inventory.android.backup.exporters.BackupFileExporter.exportTo(BackupFileExporter.java:24) 
        at net.twisterrob.inventory.android.backup.exporters.BackupDirExporter.exportTo(BackupDirExporter.java:24) 
        at net.twisterrob.inventory.android.backup.concurrent.BackupService.onHandleIntent(BackupService.java:140) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by TWiStErRob** [comment]
Implemented permission handling in svn@3130
