### ISSUE TITLE
Strange grant result because `READ_EXTERNAL_STORAGE` is API 16+

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#162]
```
V/BackupPermissions: Grant result contains unknown permission result: [-1, 0]
    net.twisterrob.java.exceptions.StackTrace
        at net.twisterrob.inventory.android.backup.BackupPermissions.onRequestPermissionsResult(BackupPermissions.java:103)
        at net.twisterrob.inventory.android.activity.BackupActivity.onRequestPermissionsResult(BackupActivity.java:214)
        at android.support.v4.app.ActivityCompat$1.run(ActivityCompat.java:378)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TWiStErRob** [comment]
Confirmed good on 16

**Comment by TWiStErRob** [comment]
Don't request permission when not necessary (i.e. doesn't exists), fixed by assuming READ permission as granted on API <16 in svn@3153
