### ISSUE TITLE
Crash from background

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#166]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.twisterrob.inventory.debug, PID: 7191
    java.lang.IllegalStateException: Not allowed to start service Intent { act=net.twisterrob.inventory.action.UPDATE_LANGUAGE pkg=net.twisterrob.inventory.debug (has extras) }: app is in background uid UidRecord{af72e61 u0a229 CAC  bg:+3m52s273ms idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
        at android.app.ContextImpl.startService(ContextImpl.java:1571)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at net.twisterrob.inventory.android.App.updateLanguage(App.java:74)
        at net.twisterrob.inventory.android.App.onConfigurationChanged(App.java:69)
        at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:5437)
        at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5637)
        at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5560)
        at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by TWiStErRob** [comment]
Repro: while starting ui test
Repro:
 * home screen
 * start app
 * home screen
 * rotate

**Comment by TWiStErRob** [comment]
Best bet is to implement one of these solutions: [Runtime exception Android O with boot_completed
](https://stackoverflow.com/a/44505719/253468)
https://commonsware.com/blog/2017/06/12/action_boot_completed-intentservice-android-8p0.html

Referenced from [How to detect process foreground for Android O
](https://stackoverflow.com/q/45915959/253468)

**Comment by TWiStErRob** [comment]
Workaround in svn@3170 just ignores the exception for now.

**Comment by TWiStErRob** [comment]
Maybe androidx.core.app.JobIntentService#enqueueWork helps here?
