### ISSUE TITLE
Cannot clear data after AndroidX

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#188]
```
    Process: net.twisterrob.inventory.debug:managespace, PID: 23990
    java.lang.IllegalStateException: Fragment net.twisterrob.inventory.android.activity.space.ConfirmedCleanAction must be a public static class to be  properly recreated from instance state.
        at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:249)
        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:180)
        at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:171)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:180)
        at net.twisterrob.inventory.android.activity.space.ManageSpaceActivity$11.onClick(ManageSpaceActivity.java:247)
        at android.view.View.performClick(View.java:4756)
        at android.view.View$PerformClick.run(View.java:19749)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by TWiStErRob** [comment]
Obsoleted by #278
