### ISSUE TITLE
ItemEditActivityTest_Edit.testCancel fails sometimes

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#217]
```
net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit > testCancel[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError:
	Expected: activity finishing is <true>
```
Tried to fix it with twisterrob/net.twisterrob.libraries#13, but even after it was failing the same.

**Comment by TWiStErRob** [comment]
It's failing 20% of the time, and when it does it shows
![image](https://user-images.githubusercontent.com/2906988/226784323-6c915e2c-0042-43d3-95bd-ffe2870671e1.png)
which is unexpected

**Comment by TWiStErRob** [comment]
success
```
TestRunner               I  started: testCancel13(net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit)
BaseEditFragment         W  name.addTextChangedListener: isClean=true, setting false
BaseEditFragment         W  setCurrentImage: isClean=false, setting false
BaseEditFragment         W  description.addTextChangedListener: isClean=false, setting false
BaseEditFragment         W  type.setOnItemSelectedListener: isClean=false, keeping (-1, 208)
BaseEditFragment         W  post: isClean=false, setting true
BaseEditFragment         W  type.setOnItemSelectedListener: isClean=true, keeping (208, 208)
BaseEditFragment         W  isDirty: isClean=true
TestRunner               I  finished: testCancel13(net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit)
```
failure
```
TestRunner               I  started: testCancel14(net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit)
BaseEditFragment         W  type.setOnItemSelectedListener: isClean=true, keeping (-1, 0)
BaseEditFragment         W  name.addTextChangedListener: isClean=true, setting false
BaseEditFragment         W  setCurrentImage: isClean=false, setting false
BaseEditFragment         W  description.addTextChangedListener: isClean=false, setting false
BaseEditFragment         W  post: isClean=false, setting true
BaseEditFragment         W  type.setOnItemSelectedListener: isClean=true, setting false (0, 208)
BaseEditFragment         W  isDirty: isClean=false
TestRunner               E  failed: testCancel14(net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit)
TestRunner               E  ----- begin exception -----
TestRunner               E  java.lang.AssertionError: 
                            Expected: activity finishing is <true>
                                 but: is finishing was <false>
                            	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
                            	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
                            	at net.twisterrob.inventory.android.test.actors.ActivityActor.assertClosing(ActivityActor.java:48)
                            	at net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit.testCancel14(ItemEditActivityTest_Edit.java:135)
TestRunner               E  ----- end exception -----
TestRunner               I  finished: testCancel14(net.twisterrob.inventory.android.activity.ItemEditActivityTest_Edit)
```

**Comment by TWiStErRob** [comment]
Note: someone reported that backing out the edit asks to confirm discard, even when didn't edit. Same root cause.

**Comment by TWiStErRob** [comment]
Artificially delaying Loaders.Categories does nothing, categories are still immediately visible.

**Comment by TWiStErRob** [comment]
This is still with no increased time, but looks promising that increased time between 7 and 9 will help to repro.
![image](https://user-images.githubusercontent.com/2906988/232003399-9b589ce7-0bc7-4b1c-8313-55c415511197.png)

**Comment by TWiStErRob** [comment]
Yep, immediate repro:
![image](https://user-images.githubusercontent.com/2906988/232004285-acc448d5-a6f7-428c-8ab1-fe056e9be52a.png)

**Comment by TWiStErRob** [comment]
https://play.google.com/console/u/0/developers/7995455198986011414/app/4974852622245161228/user-feedback/review-details?reviewId=b10c4f58-5150-4b3b-a775-bdc9af648b91&corpus=PUBLIC_REVIEWS
