### ISSUE TITLE
Manage Space confirmation dialogs broken

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#237]
![image](https://user-images.githubusercontent.com/2906988/224407475-7f892cbf-339e-48a6-8788-2fd244e42b3e.png)
should display a confirmation dialog, but it crashes

![image](https://user-images.githubusercontent.com/2906988/224407527-a016a2b4-b9f3-4c64-a3b6-e3aa127b2649.png)

```
java.lang.IllegalStateException: Fragment net.twisterrob.inventory.android.activity.space.ConfirmedCleanAction must be a public static class to be  properly recreated from instance state.
                                                                                                   	at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:249)
                                                                                                   	at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:180)
                                                                                                   	at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:171)
                                                                                                   	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:180)
                                                                                                   	at net.twisterrob.inventory.android.activity.space.ManageSpaceActivity$11.onClick(ManageSpaceActivity.java:247)
                                                                                                   	at android.view.View.performClick(View.java:4756)
                                                                                                   	at android.view.View$PerformClick.run(View.java:19749)
                                                                                                   	at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                   	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                   	at android.os.Looper.loop(Looper.java:135)
                                                                                                   	at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                                   	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   	at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by TWiStErRob** [comment]
Duplicate of #188
