### ISSUE TITLE
Backup unbind fails

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#251]
Repro:
1. Start backup
2. while in progress, back out of BackupActivity

```
java.lang.RuntimeException: Unable to unbind to service net.twisterrob.inventory.android.backup.concurrent.BackupService@1e5cbdb with Intent { cmp=net.twisterrob.inventory.debug/net.twisterrob.inventory.android.backup.concurrent.BackupService }: java.lang.IllegalStateException: Unexpected intent action: Intent { cmp=net.twisterrob.inventory.debug/net.twisterrob.inventory.android.backup.concurrent.BackupService }
	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4560)
	at android.app.ActivityThread.-$$Nest$mhandleUnbindService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2171)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: Unexpected intent action: Intent { cmp=net.twisterrob.inventory.debug/net.twisterrob.inventory.android.backup.concurrent.BackupService }
	at net.twisterrob.inventory.android.backup.concurrent.BackupService.getProgressType(BackupService.java:150)
	at net.twisterrob.inventory.android.backup.concurrent.BackupService.buildNotification(BackupService.java:116)
	at net.twisterrob.inventory.android.backup.concurrent.BackupService.buildNotification(BackupService.java:32)
	at net.twisterrob.inventory.android.backup.concurrent.NotificationProgressService.startNotification(NotificationProgressService.java:186)
	at net.twisterrob.inventory.android.backup.concurrent.NotificationProgressService.onUnbind(NotificationProgressService.java:164)
	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4544)
	at android.app.ActivityThread.-$$Nest$mhandleUnbindService(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2171) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by TWiStErRob** [comment]
Caused by 16c06a30: https://github.com/TWiStErRob/net.twisterrob.inventory/commit/16c06a307bfba3d08bdd2a26d5e47443441709d6#diff-85d9f227e6ce1af6c93a6461a9e4642a39d0029d896cd14ffe2d99afdf462b11R147

Related #164  or support 28 upgrade.
