### ISSUE TITLE
Crash when de-selecting text in About

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#269]
1. Go to About & Help
2. Double-click to select a word
3. Tap elsewhere to deselect

```
 3452-3452  AndroidRuntime           E  FATAL EXCEPTION: main
                                        Process: net.twisterrob.inventory.debug, PID: 3452
                                        java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 9111]
                                        	at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
                                        	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
                                        	at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4260)
                                        	at android.widget.Editor$HandleView.updatePosition(Editor.java:3708)
                                        	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2507)
                                        	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                        	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                        	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                        	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                        	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                        	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                        	at android.view.Choreographer.doFrame(Choreographer.java:606)
                                        	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                        	at android.os.Handler.handleCallback(Handler.java:739)
                                        	at android.os.Handler.dispatchMessage(Handler.java:95)
                                        	at android.os.Looper.loop(Looper.java:148)
                                        	at android.app.ActivityThread.main(ActivityThread.java:5417)
                                        	at java.lang.reflect.Method.invoke(Native Method)
                                        	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by TWiStErRob** [comment]
No repro on 24, 25, 26, 28, 30. Only affects 21 and 23. I'll not fix this as the workarounds are hacky and would be beneficial to very low number of users.
