### ISSUE TITLE
Documents was still open at the end of the test

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#323]

**Comment by TWiStErRob** [comment]
https://github.com/TWiStErRob/net.twisterrob.inventory/pull/321/checks?check_run_id=16222722547

testExportPickerDoesNotReappearWhenRotated (net.twisterrob.inventory.android.activity.BackupActivityTest_Export) failed
/Users/runner/work/net.twisterrob.inventory/net.twisterrob.inventory/android/build/outputs/androidTest-results/connected/debug/TEST-test(AVD) - 5.0.2-_android-.xml [took 11s]


```
java.lang.AssertionError: [com.android.documentsui, com.google.android.documentsui] was still open at the end of the test, pressing Back 1 times and Home 0 times helped kill it.
at org.junit.Assert.fail(Assert.java:89)
at net.twisterrob.inventory.android.test.ExternalAppKiller.after(ExternalAppKiller.java:78)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.lang.Thread.run(Thread.java:818)
```
